class Butterfly {
  String id; // Auto-generated by Firestore
  String name;
  String description;
  String imageUrl;
  String pdfUrl;
  String caption;
  String geolocation;
  String classification;

  Butterfly({
    required this.id,
    required this.name,
    required this.description,
    required this.imageUrl,
    required this.pdfUrl,
    required this.caption,
    required this.geolocation,
    required this.classification,
  });

  // Factory method to create a Butterfly instance from a Firestore document
  factory Butterfly.fromFirestore(Map<String, dynamic> doc) {
    return Butterfly(
      id: doc['id'] ?? '',
      name: doc['name'] ?? '',
      description: doc['description'] ?? '',
      imageUrl: doc['imageUrl'] ?? '',
      pdfUrl: doc['pdfUrl'] ?? '',
      caption: doc['caption'] ?? '',
      geolocation: doc['geolocation'] ?? '',
      classification: doc['classification'] ?? '',
    );
  }

  // Convert a Butterfly instance to a map for Firestore
  Map<String, dynamic> toFirestore() {
    return {
      'id': id,
      'name': name,
      'description': description,
      'imageUrl': imageUrl,
      'pdfUrl': pdfUrl,
      'caption': caption,
      'geolocation': geolocation,
      'classification': classification,
    };
  }
}
